version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shop
    volumes:
      - ./database:/var/lib/postgresql/data
